name: Check Fast Forward Staging to Main on Buffer PR

on:
  pull_request:
    branches:
    - buffer

jobs:
  check-fast-forward:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Attempt fast-forward merge
        run: |
          git merge --ff-only origin/staging || exit 1

      - name: Set status check
        if: success()
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=success \
            -f context="Fast Forward Check" \
            -f description="Fast forward merge is possible"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set status check failure
        if: failure()
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=failure \
            -f context="Fast Forward Check" \
            -f description="Fast forward merge is not possible"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

