name: Fast Forward Staging to Main on Buffer PR Merge

on:
  pull_request:
    # types: [synchronize, opened, reopened, closed]
    branches:
    - buffer

jobs:
  check-fast-forward:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'buffer'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Attempt fast-forward merge
        run: |
          git merge --ff-only origin/staging || exit 1

      - name: Set status check
        if: success()
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=success \
            -f context="Fast Forward Check" \
            -f description="Fast forward merge is possible"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set status check failure
        if: failure()
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state=failure \
            -f context="Fast Forward Check" \
            -f description="Fast forward merge is not possible"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fast-forward:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'buffer' && github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    needs: check-fast-forward
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'buffer'

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Fast-forward target branch
        run: |
          git checkout main
          git merge --ff-only origin/staging
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
